"""Read-only verification of the PDF generated by the named Windows virtual queue."""
import json
import math
import re
import sys
from pathlib import Path
from pypdf import PdfReader

directory = Path(sys.argv[1])
result = json.loads((directory / "result.json").read_text(encoding="utf-8"))
pdf = PdfReader(directory / "receipt.pdf")
assert len(pdf.pages) == result["expectedPages"], "Windows PDF page count differs from the prepared page plan"
text = "\n".join(page.extract_text() for page in pdf.pages)
items = re.findall(r"Item\s+(\d{3})", text)
expected_items = [f"{i:03}" for i in range(1, result["expectedItems"] + 1)]
# The Windows PDF driver may convert some runs into native-resolution image bands,
# which have no extractable text. All rendered pages also need visual QA.
assert items == sorted(set(items)), "Extractable PDF items duplicated or out of order"
assert set(items).issubset(expected_items), "Unexpected item in PDF text"
layout = json.loads((directory / "layout.json").read_text(encoding="utf-8"))
saved_text = "\n".join(run["Text"] for run in layout["Text"])
assert re.findall(r"Item\s+(\d{3})", saved_text) == expected_items, "Saved fixture missing or duplicating an item"
images = sum(len(page.images) for page in pdf.pages)
image_bands = []
for page in pdf.pages:
    def inspect_image(operator, args, matrix, text_matrix):
        if operator != b"Do":
            return
        obj = page["/Resources"].get("/XObject", {}).get(args[0])
        if obj is None:
            return
        obj = obj.get_object()
        if obj.get("/Subtype") != "/Image":
            return
        width_pt, height_pt = math.hypot(*matrix[:2]), math.hypot(*matrix[2:4])
        dpi_x, dpi_y = obj["/Width"] * 72 / width_pt, obj["/Height"] * 72 / height_pt
        assert abs(dpi_x - result["driverDpi"]) < 1 and abs(dpi_y - result["driverDpi"]) < 1, "Driver lowered image resolution"
        assert height_pt < 24, "Unexpected large raster region in the text/vector receipt"
        image_bands.append({"pixels": [obj["/Width"], obj["/Height"]], "dpi": [round(dpi_x), round(dpi_y)]})
    page.extract_text(visitor_operand_before=inspect_image)
assert len(image_bands) == images, "Image resources were not fully inspected"
print(json.dumps({
    "ok": True, "pages": len(pdf.pages), "savedItems": len(expected_items), "extractablePdfItems": len(items),
    "visualReviewRequired": True,
    "driverRasterizedTextBands": image_bands,
    "pageSizesPt": [[float(page.mediabox.width), float(page.mediabox.height)] for page in pdf.pages],
    "windowsJobId": result["spoolerJobId"], "windowsStatus": result["WindowsStatus"],
}))
